---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demopro4-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: demopro4
  template:
    metadata:
      labels:
        app: demopro4
    spec:
      containers:
      - name: demopro4-container
        image: karishma027/demopro4
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: demopro4-service
spec:
  type: LoadBalancer
  selector:
    app: demopro4
  ports:
  - port: 80
    targetPort: 3000